name: Minimalne CI - plik tekstowy

on:
  push:
    paths:
      - 'src/**'

jobs:
    echo-test:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout kodu
        uses: actions/checkout@v3

      - name: Wypisz zawartosc katalogu
        run: ls -la

      # - name: nowy krok zadanie 7
        # run: npx eslint . --ext .js,.jsx,.ts,.tsx
        
      - name: Komunikat koncowy
        run: echo "GitHub Actions dziala poprawnie 🎉"